// <auto-generated />
using System;
using BeTaskManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeTaskManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250710080028_NewDB")]
    partial class NewDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeTaskManagement.Models.BeTask", b =>
                {
                    b.Property<int>("BeTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BeTaskId"));

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextActionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BeTaskId");

                    b.HasIndex("AssignedToUserId");

                    b.ToTable("BeTasks");

                    b.HasData(
                        new
                        {
                            BeTaskId = 1,
                            CreatedOn = new DateTime(2025, 7, 10, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is just a mockup task.",
                            DueDate = new DateTime(2025, 7, 14, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mockup Task",
                            NextActionDate = new DateTime(2025, 7, 15, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "ToDo",
                            Type = "Feature"
                        });
                });

            modelBuilder.Entity("BeTaskManagement.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReminderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("TaskId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("BeTaskManagement.Models.CommentHistory", b =>
                {
                    b.Property<int>("CommentHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentHistoryId"));

                    b.Property<string>("ChangedProperty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentHistoryId");

                    b.HasIndex("CommentId");

                    b.ToTable("CommentHistories");
                });

            modelBuilder.Entity("BeTaskManagement.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            EmailAddress = "johndoe@test.test",
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            UserId = 2,
                            EmailAddress = "mm@test.test",
                            FirstName = "Maria",
                            LastName = "Marinova"
                        },
                        new
                        {
                            UserId = 3,
                            EmailAddress = "lila@test.test",
                            FirstName = "Lilly",
                            LastName = "Alan"
                        });
                });

            modelBuilder.Entity("BeTaskManagement.Models.BeTask", b =>
                {
                    b.HasOne("BeTaskManagement.Models.User", "AssignedTo")
                        .WithMany("BeTasks")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedTo");
                });

            modelBuilder.Entity("BeTaskManagement.Models.Comment", b =>
                {
                    b.HasOne("BeTaskManagement.Models.BeTask", "BeTask")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeTask");
                });

            modelBuilder.Entity("BeTaskManagement.Models.CommentHistory", b =>
                {
                    b.HasOne("BeTaskManagement.Models.Comment", "Comment")
                        .WithMany("History")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("BeTaskManagement.Models.BeTask", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("BeTaskManagement.Models.Comment", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("BeTaskManagement.Models.User", b =>
                {
                    b.Navigation("BeTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
